http://www.darulabrornw.com/* http://www.darulabrornw.com/:splat 301!

# Optional: Redirect default Netlify subdomain to primary domain
http://darulabror.netlify.com/* http://www.darulabrornw.com/:splat 301!
